monolog:
    channels: ['deprecation', 'consultation',projet,'projetHasConsultation']


when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event","!consultation","!deprecation"]
            deprecation:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
                max_files: 2
                channels: [deprecation]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            consultation:
                type: stream
                level: debug
                path:     '%kernel.logs_dir%/consultation.log'
                channels: "consultation"
            projet:
                type: stream
                level: debug
                path:     '%kernel.logs_dir%/projet.log'
                channels: "projet"
            projetHasConsultation:
                type: stream
                level: debug
                path:     '%kernel.logs_dir%/projetHasConsultation.log'
                channels: "projetHasConsultation"


when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
